//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Custom
{
    [Serializable]
    public class All_landmarksMsg : Message
    {
        public const string k_RosMessageName = "custom_msgs/All_landmarks";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public string hand;
        public double score;
        public HandLandmarkMsg[] landmarks;

        public All_landmarksMsg()
        {
            this.header = new HeaderMsg();
            this.hand = "";
            this.score = 0.0;
            this.landmarks = new HandLandmarkMsg[0];
        }

        public All_landmarksMsg(HeaderMsg header, string hand, double score, HandLandmarkMsg[] landmarks)
        {
            this.header = header;
            this.hand = hand;
            this.score = score;
            this.landmarks = landmarks;
        }

        public static All_landmarksMsg Deserialize(MessageDeserializer deserializer) => new All_landmarksMsg(deserializer);

        private All_landmarksMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.hand);
            deserializer.Read(out this.score);
            deserializer.Read(out this.landmarks, HandLandmarkMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.hand);
            serializer.Write(this.score);
            serializer.WriteLength(this.landmarks);
            serializer.Write(this.landmarks);
        }

        public override string ToString()
        {
            return "All_landmarksMsg: " +
            "\nheader: " + header.ToString() +
            "\nhand: " + hand.ToString() +
            "\nscore: " + score.ToString() +
            "\nlandmarks: " + System.String.Join(", ", landmarks.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
