//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Custom
{
    [Serializable]
    public class HandLandmarkMsg : Message
    {
        public const string k_RosMessageName = "custom_msgs/HandLandmark";
        public override string RosMessageName => k_RosMessageName;

        public long id;
        public double x;
        public double y;
        public double z;

        public HandLandmarkMsg()
        {
            this.id = 0;
            this.x = 0.0;
            this.y = 0.0;
            this.z = 0.0;
        }

        public HandLandmarkMsg(long id, double x, double y, double z)
        {
            this.id = id;
            this.x = x;
            this.y = y;
            this.z = z;
        }

        public static HandLandmarkMsg Deserialize(MessageDeserializer deserializer) => new HandLandmarkMsg(deserializer);

        private HandLandmarkMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
        }

        public override string ToString()
        {
            return "HandLandmarkMsg: " +
            "\nid: " + id.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
